In [ ]:
import (
	"fmt"
	"math"
    "runtime"
)



In [43]:


func split(sum int) (x, y int) { // 类型在变量名之后；当两个或多个连续的函数命名参数是同一类型，
                                //则除了最后一个类型之外，其他都可以省略。
    x = sum*2
    y = sum*3
    return            // 这里返回值被命名为sum， return 不加参数直接返回的其实是x,y，不同于python 返回的是空
}


func varsample(){
    var i, j int = 1, 2
    var x,y int
    k := 3 //函数外的每个语句都必须以关键字开始（`var`、`func`、等等），`:=` 结构不能使用在函数外。
}

/* 常量的定义与变量类似，只不过使用 const 关键字。

常量可以是字符、字符串、布尔或数字类型的值。

常量不能使用 := 语法定义。 */

const PI=3.14 

const (
	Big   = 1 << 100 //数值常量是高精度的
	Small = Big >> 99
)
func needInt(x int) int { return x*10 + 1 }
func needFloat(x float64) float64 {
    return x * 0.1
}


type Vertex struct {
	Lat, Long float64
}

var m1 map[string]Vertx //map 在使用之前必须用 make 而不是 new 来创建；值为 nil 的 map 是空的，并且不能赋值。
//m1 := make(map[string]Vertx)
var m = map[string]Vertex{
	"Bell Labs": Vertex{
		40.68433, -74.39967,
	},
	"Google": Vertex{
		37.42202, -122.08408,
	},
}


/*
m["Answer"] = 48
	fmt.Println("The value:", m["Answer"])

	delete(m, "Answer")
	fmt.Println("The value:", m["Answer"])

	v, ok := m["Answer"] //通过双赋值检测某个键存在：

	fmt.Println("The value:", v, "Present?", ok)
*/


In [47]:
func main(){
    fmt.Println(math.Pi) //首字母大写 才会被导出
    
    fmt.Println(split(3))
    
    var i int
	var f float64
	var b bool
	var s string
	fmt.Printf("%v %v %v %q\n", i, f, b, s)
    

    
    fmt.Println(needInt(Small))
    //fmt.Println(needInt(Big))
	fmt.Println(needFloat(Small))
	fmt.Println(needFloat(Big))
    
    
    //数组
    p := []int{0,1,2,3,4,5}
    fmt.Println(p[:3])
    fmt.Println(p[:])
    fmt.Println(p[3:])
    fmt.Println(p[1:3])

}

main()

3.141592653589793
6 9
0 0 false ""
21
0.2
0
[0 1 2]
[0 1 2 3 4 5]
[3 4 5]
[1 2]
